//export const CHANGE_NAME = 'CHANGE_NAME';

export const GET_HOTPROLIST = 'GET_HOTPROLIST'
export const GET_SPECIALPROLIST = 'GET_SPECIALPROLIST'
export const GET_INDEXINFO = 'GET_INDEXINFO'
export const GET_GOODSLIST = 'GET_GOODSLIST'
export const GET_GOODSDETAIL = 'GET_GOODSDETAIL'
export const CHANGE_ANIMATING = 'CHANGE_ANIMATING'
export const CHANGE_SHOW = 'CHANGE_SHOW'
export const CHANGE_SHOWSTR = 'CHANGE_SHOWSTR'
export const CHANGE_UPDATESTATE = 'CHANGE_UPDATESTATE'
export const CHANGE_UPDATE = 'CHANGE_UPDATE'
export const CLEAN_SPECIALPROLIST = 'CLEAN_SPECIALPROLIST'

